repos:
-   repo: local
    hooks:
    -   id: ruff-format
        name: ruff-format
        entry: poetry run ruff format
        language: system
        types: [ python ]
        stages: [ commit ]
        files: ^(src/|tests/|bin/)
    -   id: ruff
        name: ruff
        entry: poetry run ruff check --fix
        language: system
        types: [ python ]
        stages: [ commit ]
        files: ^(src/|tests/|bin/)
    -   id: flake8
        name: flake8
        entry: flake8 src/ tests/
        language: system
        stages: [ commit ]